// Command pki-gen generates the post-quantum branch of the testbed PKI with
// crypto/x509 and crypto/mldsa: a simulated SMO root, an SMO onboarding CA, the RIC
// intermediate CA and TLS server certificates, all signed with ML-DSA (FIPS 204).
//
// The classical branch is still generated by ca/scripts/gen-pki.sh with OpenSSL;
// OpenSSL 1.1.1 on the lab VM predates ML-DSA, which is why this tool exists.
package main

import (
	"crypto"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"flag"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/oran-ricsec/xapp-token-binding/internal/pki"
)

type serviceFlag []string

func (s *serviceFlag) String() string { return strings.Join(*s, ",") }
func (s *serviceFlag) Set(v string) error {
	*s = append(*s, v)
	return nil
}

func main() {
	out := flag.String("out", "out/pki", "output directory")
	org := flag.String("org", "O-RAN-RIC", "organization")
	clusterDomain := flag.String("cluster-domain", "cluster.local", "Kubernetes cluster domain")
	rootAlg := flag.String("root-alg", "ML-DSA-87", "root CA key algorithm")
	caAlg := flag.String("ca-alg", "ML-DSA-65", "intermediate CA key algorithm")
	serverAlg := flag.String("server-alg", "ML-DSA-65", "server certificate key algorithm")
	rootDays := flag.Int("root-days", 3650, "root CA validity in days")
	caDays := flag.Int("ca-days", 1825, "intermediate CA validity in days")
	serverDays := flag.Int("server-days", 365, "server certificate validity in days")
	var services serviceFlag
	flag.Var(&services, "service", "server certificate to issue, as name:namespace (repeatable)")
	flag.Parse()

	if err := run(*out, *org, *clusterDomain, *rootAlg, *caAlg, *serverAlg, *rootDays, *caDays, *serverDays, services); err != nil {
		fmt.Fprintln(os.Stderr, "pki-gen:", err)
		os.Exit(1)
	}
}

type issuer struct {
	cert *x509.Certificate
	key  crypto.Signer
}

func run(out, org, clusterDomain, rootAlg, caAlg, serverAlg string, rootDays, caDays, serverDays int, services []string) error {
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	if _, err := os.Stat(filepath.Join(out, "ric-intermediate-ca-pq.crt")); err == nil {
		fmt.Printf("post-quantum PKI already present in %s (remove the files to regenerate)\n", out)
		return nil
	}

	root, err := selfSignedCA(out, "smo-root-ca-pq", rootAlg,
		pkix.Name{Organization: []string{org}, OrganizationalUnit: []string{"SMO"}, CommonName: "SMO Root CA PQ (simulated)"}, rootDays)
	if err != nil {
		return fmt.Errorf("root CA: %w", err)
	}
	onboarding, err := subCA(out, "smo-onboarding-ca-pq", caAlg,
		pkix.Name{Organization: []string{org}, OrganizationalUnit: []string{"SMO"}, CommonName: "SMO Onboarding CA PQ (simulated)"}, caDays, root)
	if err != nil {
		return fmt.Errorf("onboarding CA: %w", err)
	}
	intermediate, err := subCA(out, "ric-intermediate-ca-pq", caAlg,
		pkix.Name{Organization: []string{org}, OrganizationalUnit: []string{"Near-RT RIC"}, CommonName: "RIC Intermediate CA PQ"}, caDays, root)
	if err != nil {
		return fmt.Errorf("intermediate CA: %w", err)
	}
	_ = onboarding

	for _, svc := range services {
		name, ns, ok := strings.Cut(svc, ":")
		if !ok {
			return fmt.Errorf("-service %q is not name:namespace", svc)
		}
		dns := []string{
			fmt.Sprintf("%s.%s.svc.%s", name, ns, clusterDomain),
			fmt.Sprintf("%s.%s.svc", name, ns),
			fmt.Sprintf("%s.%s", name, ns),
			name, "localhost",
		}
		if err := serverCert(out, name+"-server-pq", serverAlg,
			pkix.Name{Organization: []string{org}, OrganizationalUnit: []string{"Near-RT RIC"}, CommonName: dns[0]},
			dns, serverDays, intermediate); err != nil {
			return fmt.Errorf("%s server certificate: %w", name, err)
		}
	}

	// Trust bundle: the RIC intermediate is the anchor relying parties are configured with.
	bundle := append(pki.EncodeCertsPEM(intermediate.cert), pki.EncodeCertsPEM(root.cert)...)
	if err := os.WriteFile(filepath.Join(out, "ric-ca-bundle-pq.crt"), bundle, 0o644); err != nil {
		return err
	}
	fmt.Printf("post-quantum PKI written to %s (root %s, CAs %s, servers %s)\n", out, rootAlg, caAlg, serverAlg)
	return nil
}

func serial() (*big.Int, error) {
	return rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 127))
}

func write(out, name string, cert *x509.Certificate, key crypto.Signer, chain ...*x509.Certificate) error {
	if err := os.WriteFile(filepath.Join(out, name+".crt"), pki.EncodeCertsPEM(cert), 0o644); err != nil {
		return err
	}
	keyPEM, err := pki.EncodePrivateKeyPEM(key)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(out, name+".key"), keyPEM, 0o600); err != nil {
		return err
	}
	if len(chain) > 0 {
		full := append(pki.EncodeCertsPEM(cert), pki.EncodeCertsPEM(chain...)...)
		if err := os.WriteFile(filepath.Join(out, name+"-chain.crt"), full, 0o644); err != nil {
			return err
		}
	}
	fmt.Println("  ", name+":", pki.DescribeCert(cert))
	return nil
}

func selfSignedCA(out, name, alg string, subject pkix.Name, days int) (*issuer, error) {
	key, err := pki.GenerateKey(alg)
	if err != nil {
		return nil, err
	}
	sn, err := serial()
	if err != nil {
		return nil, err
	}
	tmpl := &x509.Certificate{
		SerialNumber: sn, Subject: subject,
		NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().AddDate(0, 0, days),
		IsCA: true, BasicConstraintsValid: true,
		KeyUsage: x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, key.Public(), key)
	if err != nil {
		return nil, err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, err
	}
	return &issuer{cert: cert, key: key}, write(out, name, cert, key)
}

func subCA(out, name, alg string, subject pkix.Name, days int, parent *issuer) (*issuer, error) {
	key, err := pki.GenerateKey(alg)
	if err != nil {
		return nil, err
	}
	sn, err := serial()
	if err != nil {
		return nil, err
	}
	tmpl := &x509.Certificate{
		SerialNumber: sn, Subject: subject,
		NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().AddDate(0, 0, days),
		IsCA: true, BasicConstraintsValid: true, MaxPathLen: 0, MaxPathLenZero: true,
		KeyUsage: x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, parent.cert, key.Public(), parent.key)
	if err != nil {
		return nil, err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, err
	}
	return &issuer{cert: cert, key: key}, write(out, name, cert, key, parent.cert)
}

func serverCert(out, name, alg string, subject pkix.Name, dnsNames []string, days int, parent *issuer) error {
	key, err := pki.GenerateKey(alg)
	if err != nil {
		return err
	}
	sn, err := serial()
	if err != nil {
		return err
	}
	tmpl := &x509.Certificate{
		SerialNumber: sn, Subject: subject,
		NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().AddDate(0, 0, days),
		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		DNSNames:              dnsNames,
		IPAddresses:           []net.IP{net.ParseIP("127.0.0.1")},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, parent.cert, key.Public(), parent.key)
	if err != nil {
		return err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return err
	}
	return write(out, name, cert, key, parent.cert)
}
